# Generated by Django 3.2.4 on 2021-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=200, null=True)),
                ('mdate', models.CharField(blank=True, max_length=50, null=True)),
                ('edate', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
