# Generated by Django 3.2.4 on 2021-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isdist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField(db_column='Status')),
                ('username', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'IsDist',
                'managed': False,
            },
        ),
    ]
