# Generated by Django 3.2.4 on 2021-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.FloatField()),
                ('proflepic', models.FileField(blank=True, default='images/default.png', null=True, upload_to='profiles/user/')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userdetails',
                'managed': False,
            },
        ),
    ]
